In [9]:
import time
import numpy as np
import torch
import tensorflow as tf

C:\Users\SUSHIL KUMAR SAHOO\AppData\Roaming\Python\Python310\site-packages\google\api_core\_python_version_support.py:273: FutureWarning: You are using a Python version (3.10.20) which Google will stop supporting in new releases of google.api_core once it reaches its end of life (2026-10-04). Please upgrade to the latest Python version, or at least Python 3.11, to continue receiving updates for google.api_core past that date.
  warnings.warn(message, FutureWarning)


In [10]:
def arr_multiplication(type_arr, arr1, arr2):
    t1 = time.perf_counter()
    
    if type_arr == 'np_arr':
        res = np.dot(arr1, arr2)
    elif type_arr == 'torch_arr':
        res = torch.matmul(arr1, arr2)
        if arr1.is_cuda:
            torch.cuda.synchronize()  # Wait for GPU computation to complete
    else:
        # tf.tensordot handles 1D vector dot product
        res = tf.tensordot(arr1, arr2, axes=1)
        
    t2 = time.perf_counter()
    time_diff = t2 - t1
    print(f"{type_arr} result: {res} | time_taken: {time_diff:.6f} s")


In [11]:
# 1. NumPy (float64)
np_arr = np.arange(1000000, dtype=np.float64)
np_arr2 = np_arr * 23 + 1 + 3
arr_multiplication('np_arr', np_arr, np_arr2)

# 2. PyTorch (float32 / float64)
device = "cuda" if torch.cuda.is_available() else "cpu"
torch_arr = torch.ones(1000000, dtype=torch.float32, device=device)
torch_arr2 = torch_arr + 230 + 21 - 2
arr_multiplication('torch_arr', torch_arr, torch_arr2)

# 3. TensorFlow (float32 / float64)
tf_arr = tf.range(1000000, dtype=tf.float32)
tf_arr2 = tf_arr + 23 + 12 + 2
arr_multiplication('tf_arr', tf_arr, tf_arr2)

np_arr result: 7.66665716666836e+18 | time_taken: 0.000834 s
torch_arr result: 250000000.0 | time_taken: 0.054728 s
tf_arr result: 3.3335072558311014e+17 | time_taken: 0.021427 s


In [12]:
res = 0
t1 = time.perf_counter()
for i in range(len(np_arr)):
    res += np_arr[i]*np_arr2[i]
t2 = time.perf_counter()
time_diff = t2 - t1
print(f"result: {res} | time_taken: {time_diff:.6f} s")

result: 7.666657166666563e+18 | time_taken: 0.224063 s


#### Cosine Similarity : 

In [13]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

sentences = [
    "The cat sat on the mat.",
    "A cat sat on a mat.",
    "Space rockets explore distant stars."
]

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(sentences)

print(f"Vocabulary : {vectorizer.get_feature_names_out()}")

similarity_matrix  = cosine_similarity(X)
print(similarity_matrix.round(2))

print(f"\nSimilarity between Sentence A and B: {similarity_matrix[0][1]:.2f}")
print(f"Similarity between Sentence A and C: {similarity_matrix[0][2]:.2f}")

Vocabulary : ['cat' 'distant' 'explore' 'mat' 'on' 'rockets' 'sat' 'space' 'stars'
 'the']
[[1.   0.71 0.  ]
 [0.71 1.   0.  ]
 [0.   0.   1.  ]]

Similarity between Sentence A and B: 0.71
Similarity between Sentence A and C: 0.00


### Matrix Transformation Using Numpy :

In [25]:
from PIL import Image


img = Image.open("image.png").convert("L")

A = np.array(img)

print("A Shape:", A.shape)
print("A Data type:", A.dtype)

B = np.clip(A + 50, 0, 255).astype(np.uint8)    # (mat_op,min,max)
print("B Shape:", B.shape)
print("B Data type:", B.dtype)

Image.fromarray(A, mode="L").show()
# Image.fromarray(B, mode="L").show()
# Image.fromarray(B-50, mode="L").show()
Image.fromarray(A-50, mode="L").show()



A Shape: (296, 295)
A Data type: uint8
B Shape: (296, 295)
B Data type: uint8


(296, 295, 3)
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[225 228 233]
  [225 228 233]
  [225 228 233]
  ...
  [207 218 234]
  [206 218 234]
  [206 218 234]]

 [[226 229 234]
  [226 229 234]
  [226 229 234]
  ...
  [206 218 233]
  [206 218 234]
  [206 218 234]]

 ...

 [[148 147 145]
  [145 143 142]
  [146 145 143]
  ...
  [114 112 109]
  [109 106 103]
  [109 106 103]]

 [[146 144 142]
  [142 140 138]
  [141 139 137]
  ...
  [122 119 118]
  [121 117 116]
  [121 117 116]]

 [[143 141 139]
  [138 136 135]
  [142 141 139]
  ...
  [121 117 116]
  [122 118 117]
  [124 120 119]]]
